### ISSUE TITLE
Apply this correction option

### ISSUE THREAD

**Issue by xxhomey19** [tbroadley/github-spellcheck-cli#27]
Hi @tbroadley,
This is an awesome cli tool. Good work!

I think **Apply this correction? y, n, d, i, e ...**  is too vague. It's difficult to determine which should I select.
It would be better to explain them more in README or CLI.
Maybe [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) is helpful.

**Comment by tbroadley** [comment]
Hi @xxhomey19! Thanks for the feedback. When you see the "Apply this correction?" prompt, if you enter `h` or just press Enter, the tool prints out a description of what each command does. That being said, it definitely isn't obvious that these descriptions exist.

I think the best way to immediately improve this situation would be to add some information to the README. I'll definitely look at Inquirer.js for the next major version, thanks for the tip!

**Comment by xxhomey19** [comment]
No problems.
