### ISSUE TITLE
Install on WSL not working 

### ISSUE THREAD

**Issue by spences10** [tbroadley/github-spellcheck-cli#36]
Hello,

I'm trying to install this via npm on Windows Subsystem Linux and get the attached error, I've tried several times now and it won't install. npm debug file follows:

[2018-01-04T16_35_04_476Z-debug.log](https://github.com/tbroadley/github-spellcheck-cli/files/1603997/2018-01-04T16_35_04_476Z-debug.log)

Also, there's mention of generating a token in GitHub but I couldn't find any documentation on where to use it.

**Comment by tbroadley** [comment]
Hi @spences10! Thanks for opening this issue. I was able to reproduce the issue that you're having with installing GitHub Spellcheck.

It seems that the error occurs during the installation of [NodeGit](https://github.com/nodegit/nodegit). To confirm, I tried to globally install [another package that depends on NodeGit](https://www.npmjs.com/package/markdown-check-deadlink). That installation failed too. I'd suggest opening an issue on NodeGit to let them know about this issue.

As a temporary workaround, you could install GitHub Spellcheck outside of LSW and use it with Powershell or Command Prompt. That's how I use it, so I'm relatively sure it'd work for you too.

Also, [I've updated the README](https://github.com/tbroadley/github-spellcheck-cli/blob/master/README.md#github-personal-access-token) to better explain how to use the GitHub personal access token.

**Comment by spences10** [comment]
Ok thanks, happy to have this closed then. I'll reference it on the nodegit ticket I guess
