### ISSUE TITLE
Option to disable automatic creation of PR

### ISSUE THREAD

**Issue by madhavarshney** [tbroadley/github-spellcheck-cli#79]
Hi there!  Amazing work on this tool 👍.  I was wondering if there's an option to not create the PR but to just push the changes to your local fork of a repository and open the compare page.  The first time I ran the tool, it only opened the GitHub compare page in my browser, which is exactly what I wanted.  The second time, though, it automatically created the pull request.  An option to just create the branch and push the changes would be great.

Thanks, Madhav.

**Comment by tbroadley** [comment]
Hey! Thanks so much 😄 This definitely sounds like a good feature. Right now a PR will be opened automatically unless the repository has a PR template.

**Comment by madhavarshney** [comment]
Oh, okay.  That makes sense as to why the PR wasn't created in another repository.

**Comment by madhavarshney** [comment]
I can submit a PR for this.  Any ideas for the option's name?  `--no-pr` / `--compare`?

**Comment by madhavarshney** [comment]
Or maybe it can be an option like `c` (for compare) at `Are you sure you want to create a pull request with these corrections?`

**Comment by tbroadley** [comment]
A PR would be great, thanks! I think a command-line option would work best. `--no-pr` sounds good to me.

**Comment by tbroadley** [comment]
It might be worth changing the "Are you sure you want to create a pull request with these corrections?" prompt to be more generic, so that it makes sense whether or not `--no-pr` was passed.
