### ISSUE TITLE
Usable for local git repos

### ISSUE THREAD

**Issue by andife** [tbroadley/github-spellcheck-cli#97]
Hello,
Is it possible to use the program for local git repos as well? (Which are not published at github)

Thank you
Andreas

**Comment by tbroadley** [comment]
Hey Andreas! Currently this tool only supports spellchecking GitHub repos, and I'm not planning to add support for this. If you're looking to spellcheck a local Git repo or a repo on another Git hosting service, I'd suggest checking out another project of mine, https://github.com/tbroadley/spellchecker-cli. It's a command-line tool for spellchecking files.
